apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: emulator
  labels:
   app: emulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emulator
  template:
    metadata:
      labels:
        app: emulator
    spec:
      containers:
      - name: emulator
        image: venkatarr/emulator
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
#      imagePullSecrets:
#      - name: acr-auth
