apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: emulator
  labels:
   app: emulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emulator
  template:
    metadata:
      labels:
        app: emulator
    spec:
      containers:
      - name: emulator
        image: 375310561132.dkr.ecr.ap-south-1.amazonaws.com/peopletech-repo:emulatoreks
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ekssecret
