apiVersion: apps/v1
kind: Deployment
metadata:
  name: emulator
  labels:
    app: emulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emulator
  template:
    metadata:
      labels:
        app: emulator
    spec:
      containers:
      - name: emulator
        image: sniaregistry.azurecr.io/emulator
      imagePullSecrets:
      - name: acr-auth
      imagepullpolicy: Always
      ports:
      - containerPort: 5000
